### ISSUE TITLE
config.js

### ISSUE THREAD

**Issue by Marsovski** [simonh1000/angular2-beta-redux-systemjs#1]
**config.js** defined in **index.html** but not include in git
```
"NetworkError: 404 Not Found - http://localhost:3000/config.js"
```

Install
- git clone https://github.com/simonh1000/angular2-beta-redux-systemjs.git
- cd angular2-beta-redux-systemjs/
- npm install
- npm start

**Comment by simonh1000** [comment]
Thanks for the issue. Push a fix - could you try again?
